name: OCaml CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-22.04
    env:
      OCAML_VERSION: "4.14.2"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "ocaml-base-compiler.${{ env.OCAML_VERSION }}"

      - name: Install system tools
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            gcc \
            make

      - name: Cache OPAM
        uses: actions/cache@v4
        with:
          path: |
            ~/.opam
            _build
          key: ${{ runner.os }}-ocaml-${{ env.OCAML_VERSION }}-${{ hashFiles('*.opam', 'dune-project') }}

      - name: Install dependencies
        run: |
          opam repo add zanuda https://github.com/Kakadu/zanuda.git
          opam update
          opam install -y dune alcotest angstrom ppx_expect zanuda
          opam install --deps-only -y .

      - name: Build
        run: dune build

      - name: Run linter
        run: zanuda -dir . -exclude _build

      - name: Run tests
        run: dune runtest

      - name: Verify ASM generation
        run: |
          echo "let f x y = x + y\nlet main = print_int (f 2 3)" > test.ml
          ./main.byte test.ml
          test -f output.s
          head -n 20 output.s

      - name: Upload generated ASM
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generated-asm
          path: output.s