name: OCaml CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "4.14.1"

      - name: Install basic build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            pkg-config

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.opam
            _build
          key: ${{ runner.os }}-ocaml-${{ hashFiles('dune-project', '*.opam') }}

      - name: Install project dependencies
        run: |
          opam update
          opam install -y dune alcotest angstrom ppx_expect
          opam install --deps-only -y .

      - name: Build project
        run: dune build

      - name: Run tests
        run: dune runtest

      - name: Verify ASM generation
        run: |
          echo "let f x y = x + y\nlet main = print_int (f 2 3)" > test.ml
          ./_build/default/main.exe test.ml
          test -f output.s
          head -n 20 output.s

      - name: Upload generated ASM
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: generated-asm
          path: output.s