name: OCaml CI

on:
  push:
    branches: [master]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "4.14.2"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            gcc \
            make

      - name: Cache OPAM
        uses: actions/cache@v3
        with:
          path: |
            ~/.opam
            _build
          key: ${{ runner.os }}-ocaml-4.14.2-${{ hashFiles('dune-project', '*.opam') }}

      - name: Install dependencies
        run: |
          opam repo add zanuda https://github.com/ocaml-platform/zanuda.git
          opam update
          opam install -y dune alcotest zanuda
          opam install --deps-only -y .

      - name: Initialize Dune project (if needed)
        run: |
          if [ ! -f dune-project ]; then
            dune init project your_project_name --libs=angstrom
          fi

      - name: Build
        run: dune build

      - name: Run tests
        run: dune runtest

      - name: Run linter
        run: zanuda -dir . -exclude _build